# docker-compose build && docker-compose up -d
version: "3"

volumes:
  pg_data:

services:
  db:
    container_name: twitter_db
    build:
      context: ./
      dockerfile: postgresql/Dockerfile
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "euro_dashboard"]

  # dashboard:
  #   build:
  #     context: ./
  #   # command: python3 app.py
  #   # command: ping 145.228.135.138
  #   env_file:
  #     - .env
  #   restart: always
  #   ports:
  #     - 5000:5000
  #   # depends_on:
  #   #   - db
